config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [ :edit, :create, :update, :destroy ]
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "projects#index"
end

app/models/activities/comment.rb
class Comment < Activity
  extend SerializerHelper
  set_required_json_fields %w[text]

  def serialize
    text
  end

  def action
    "commented"
  end
end

app/models/activities/status_update.rb
class StatusUpdate < Activity
  extend SerializerHelper
  set_required_json_fields %w[from to field]

  def serialize
    "Changed from <b>#{from.humanize}</b> to <b>#{to.humanize}</b>"
  end

  def action
    "updated the #{field}"
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  include SoftDeletable
  belongs_to :activitable, polymorphic: true
  belongs_to :user

  validates_presence_of :content, :activitable_type, :activitable_id, :user_id

  def serialize
    raise "ERROR: STI Class #{self.class.name} should implement serialize and it doesn't"
  end

  def action
    raise "ERROR: STI Class #{self.class.name} should implement action and it doesn't"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/soft_deletable.rb
module SoftDeletable
  extend ActiveSupport::Concern

  included do
    default_scope { where(deleted_at: nil) }
  end

  def delete
    update_column :deleted_at, DateTime.now if has_attribute? :deleted_at
  end

  def destroy
    callbacks_result = transaction do
      run_callbacks(:destroy) do
        delete
      end
    end
    callbacks_result ? self : false
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include SoftDeletable

  enum :status, %i[to_do active done archived]

  has_many :activities, as: :activitable

  validates :name, uniqueness: true
  validates_presence_of :name, :status
  validates_length_of :name, minimum: 1
  validates_length_of :description, minimum: 1
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true

  has_many :activities, dependent: :delete_all

  validates_presence_of :name
  validates_length_of :name, minimum: 1
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ destroy ]

  # POST /comments
  def create
    @comment = Comment.new(**comment_params, user_id: current_user.id)

    if @comment.save
      redirect_to activitable_path, notice: "Comment was successfully created."
    else
      render activitable_path, status: :unprocessable_entity
    end
  end

  # DELETE /comments/1
  def destroy
    if @comment
      @comment.destroy!
      redirect_to activitable_path, notice: "Comment was successfully destroyed.", status: :see_other
    else
      render :not_found
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.where(user: current_user).find(params.expect(:id))
    end

    def activitable_path
      comment_params["activitable_type"].constantize.find(comment_params["activitable_id"])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.expect(comment: [
        :text, :activity_id, :activitable_id, :activitable_type, :user_id
      ])
    end
end

app/controllers/projects_controller.rb
require_relative "../services/status_update_creator"
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :cache_changes, only: %i[ update ]

  CREATE_ACTIVITY_ON_CHANGE = %w[name status]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: "Project was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      create_change_activity
      redirect_to @project, notice: "Project was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy!
    redirect_to projects_path, notice: "Project was successfully destroyed.", status: :see_other
  end

  private

    def create_change_activity
      filtered_params = @changed.select { |k, v| CREATE_ACTIVITY_ON_CHANGE.include?(k) }
      return if filtered_params.empty?

      ::StatusUpdateCreator.create(@project_attrs,
                                   filtered_params,
                                   @project,
                                   current_user)
    end

    def cache_changes
      @project_attrs = @project.attributes
      ## Hash diff
      @changed = project_params
                .reject { |k, v| %w[id created_at updated_at].include?(k) }
                .reject { |k, v| @project_attrs [k] == v }
                .merge(@project_attrs .reject { |k, v| project_params.has_key?(k) }).to_h
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.includes(:activities).find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.expect(project: [ :name, :description, :status ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(name: "Dummy Persona 1")
  end
end

app/helpers/serializer_helper.rb
module SerializerHelper
  attr_reader :required_json_fields

  def set_required_json_fields(keys)
    @required_json_fields = keys
    store_accessor :content, @required_json_fields
    validates_presence_of @required_json_fields
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Project Comment Component
    meta name="keywords" content="template language"
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="mobile-web-app-capable" content="yes"
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    link rel="icon" href="/icon.png" type="image/png"
    link rel="icon" href="/icon.svg" type="image/svg+xml"
    link rel="apple-touch-icon" href="/icon.png"

    = stylesheet_link_tag :app
    = javascript_importmap_tags

  body
    main class="container mx-auto mt-28 px-5"
      == yield

app/views/projects/_activity.html.slim
ol.relative.border-s.border-gray-200.dark:border-gray-700
  - @project.activities.includes(:user).order(created_at: :desc).each_with_index do |activity, index|
      li.mb-10.ms-6
        span[class="absolute flex items-center justify-center w-6 h-6 bg-#{activity.user.color}-100 rounded-full -start-3 ring-8 ring-white dark:ring-gray-900 dark:bg-blue-900"]
        .p-4.bg-white.border.border-gray-200.rounded-lg.shadow-xs.dark:bg-gray-700.dark:border-gray-600
            .items-center.justify-between.mb-3.sm:flex
              time.mb-1.text-xs.font-normal.text-gray-400.sm:order-last.sm:mb-0
                = time_ago_in_words(activity.created_at)
                |  ago
              .text-sm.font-normal.text-gray-500.lex.dark:text-gray-300
                = activity.user.name
                = " #{activity.action}"
            - if activity.type == 'Comment'
              .p-3.text-xs.italic.font-normal.text-gray-500.border.border-gray-200.rounded-lg.bg-gray-50.dark:bg-gray-600.dark:border-gray-500.dark:text-gray-300
                .items-center.justify-between.flex
                  = activity.serialize
                  - if activity.user == current_user
                    = link_to comment_path(activity), data: { turbo_method: :delete }, class: "inline-flex items-center px-4 text-sm font-medium text-gray-900hover:bg-gray-100 hover:text-red-700 focus:z-10 focus:ring-2 focus:ring-red-700 focus:text-red-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-red-500 dark:focus:text-white" do
                      svg.w-3.h-2.me-2[aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="#000000" viewBox="0 0 448 512"]
                        path[d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"]
                      span
                        | Delete
            - else
              .p-3.text-xs.italic.font-normal.text-gray-500
                = activity.serialize.html_safe

app/views/projects/_buttons.html.slim
=< link_to projects_path, class: "inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white" do
  svg.w-5.h-5[aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#000000" viewBox="0 0 448 512"]
    path[d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"]
  span
    | Back to projects


.inline-flex.float-right.rounded-md.shadow-xs[role="group"]
  = link_to edit_project_path(@project), class: "inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white" do
    svg.w-3.h-3.me-2[aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#000000" viewBox="0 0 16 16"]
      path[d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"]
    span
      | Edit this project
  = link_to project_path(@project), data: { turbo_method: :delete }, class: "inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-e-lg hover:bg-gray-100 hover:text-red-700 focus:z-10 focus:ring-2 focus:ring-red-700 focus:text-red-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-red-500 dark:focus:text-white" do
    svg.w-3.h-3.me-2[aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="#000000" viewBox="0 0 448 512"]
      path[d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"]
    span
      | Delete this project
br
br

app/views/projects/_form.html.slim
= form_with(model: project) do |form|
  - if project.errors.any?
    div style="color: red"
      h2 = "#{pluralize(project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - project.errors.each do |error|
          li = error.full_message

  div
    strong
      = form.label :name, style: "display: block"
    = form.text_field :name, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'

  br
  div
    strong
      = form.label :description, style: "display: block"
    = form.textarea :description, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'

  br
  div
    strong
      = form.label :status, style: "display: block"
    = form.select :status, options_for_select(Project.statuses.map {|key, value| [key.titleize, Project.statuses.key(value)]}, project.status)

  br
  button.inline-flex.items-center.px-4.py-2.text-sm.font-medium.text-gray-900.bg-white.border.border-gray-200.rounded-lg.hover:bg-gray-100.hover:text-blue-700.focus:z-10.focus:ring-2.focus:ring-blue-700.focus:text-blue-700.dark:bg-gray-800.dark:border-gray-700.dark:text-white.dark:hover:text-white.dark:hover:bg-gray-700.dark:focus:ring-blue-500.dark:focus:text-white[type="button"]
    = form.submit

app/views/projects/_new_comment.html.slim
.ml-6.p-4.bg-white.border.border-gray-200.rounded-lg.shadow-xs.dark:bg-gray-700.dark:border-gray-600
  .p-3.text-g.italic.font-normal.text-gray-500.border.border-gray-200.rounded-lg.bg-gray-50.dark:bg-gray-600.dark:border-gray-500.dark:text-gray-300
    = form_with model: Comment.new, scope: :comment, html: { autocomplete: "off" }, class: "items-center justify-between gap-6 flex" do |form|
      = form.text_field :text, placeholder: 'Write your comment here...', class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
      = form.hidden_field :activitable_id,   value: @project.id
      = form.hidden_field :activitable_type, value: 'Project'
      = form.submit class: 'px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white'
br
br

app/views/projects/_no_activities.slim
p No activities yet

app/views/projects/_project.html.slim
div id="#{dom_id project}"
  h1.mb-4.text-4xl.font-extrabold.tracking-tight.text-gray-900.md:text-5xl.lg:text-6xl.dark:text-white
    =< project.name
  - if project.status == 'to_do'
    button.-translate-y-13.float-right.text-white.bg-gradient-to-r.from-blue-500.via-blue-600.to-blue-700.font-medium.rounded-lg.text-sm.px-5.py-2.5.text-center.me-2.mb-2[type="button"]
      | To Do
  - if project.status == 'active'
    button.-translate-y-13.float-right.text-white.bg-gradient-to-r.from-green-400.via-green-500.to-green-600.font-medium.rounded-lg.text-sm.px-5.py-2.5.text-center.me-2.mb-2[type="button"]
      | Active
  - if project.status == 'done'
    button.-translate-y-13.float-right.text-gray-900.bg-gradient-to-r.from-lime-200.via-lime-400.to-lime-500.font-medium.rounded-lg.text-sm.px-5.py-2.5.text-center.me-2.mb-2[type="button"]
      | Done
  - if project.status == 'archived'
    button.-translate-y-13.float-right.text-gray-900.bg-gradient-to-r.from-gray-200.via-gray-400.to-gray-500.font-medium.rounded-lg.text-sm.px-5.py-2.5.text-center.me-2.mb-2[type="button"]
      | Archived
p.mb-3.text-gray-500.dark:text-gray-400
  strong Description:
  =< project.description

app/views/projects/edit.html.slim
.inline-flex.gap-4
  div
    =< link_to projects_path, class: "inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white" do
      svg.w-5.h-5[aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#000000" viewBox="0 0 448 512"]
        path[d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"]
      span
        | Back to projects
  div
    => link_to @project, class: "inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white" do
      span
        | Show this project

strong
  h1 Editing project

== render "form", project: @project

br

app/views/projects/index.html.slim
p style="color: green" = notice

strong
  =< link_to new_project_path, class: "inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white" do
    span
      | + New project
br
h1 Existing projects:
br
#projects.grid.grid-cols-2.gap-2
  - @projects.each do |project|
    h1.text-2xl
      strong
        = project.name
    p
      => link_to project, class: "inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white" do
        span
          | Show this project

app/views/projects/new.html.slim
div
  =< link_to projects_path, class: "inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white" do
    svg.w-5.h-5[aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#000000" viewBox="0 0 448 512"]
      path[d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"]
    span
      | Back to projects

strong
  h1 Add New project

== render "form", project: @project

br

app/views/projects/show.html.slim
p style="color: green" = notice

div
  == render "buttons"
== render @project

br
br
div
  == render "new_comment"

  - if @project.activities.any?
      == render "activity"
  - else
    == render "no_activities"